### ISSUE TITLE
Pages on `docs.beakerbrowser.com` are rendered incorrectly

### ISSUE THREAD

**Issue by antonalekseev** [beakerbrowser/beaker-browser.gitbook.io#7]
Due to the CORS policy which prevents browser to access assets (fonts, images -- see screenshot below) hosted on `https://gstatic.gitbook.com/`.

```
downloadable font: download failed (font-family: "Roboto" style:normal weight:700 stretch:100 src index:2): bad URI or cross-site access not allowed source: https://gstatic.gitbook.com/fonts/72e37e5bf95a8dba938c78b1d7d91253.woff
```

Web server which serves `https://docs.beakerbrowser.com/` should set `Access-Control-Allow-Origin: https://gstatic.gitbook.com` on HTTP replies in order to resolve the issue.

![image](https://user-images.githubusercontent.com/2895684/83161812-71cfd180-a0f8-11ea-8854-6b42f9b23816.png)

**Comment by pfrazee** [comment]
Huh thanks for the heads up. @frabrunelle I think we should make that docs move you've been talking about

**Comment by frabrunelle** [comment]
The new docs website is now live! 🎉 

https://github.com/beakerbrowser/docs.beakerbrowser.com

**Comment by antonalekseev** [comment]
Nice one!
